name: Black

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Run black
        run: black .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: refactor
          title: refactor
          body: Automated code formatting!
          branch: autofix
          committer: AsmSafone <77989182+AsmSafone@users.noreply.github.com>
          signoff: true
          delete-branch: true
